language: node_js
branches:
  only:
    - source
node_js:
 - "node"
install:
 - npm install
script:
  - npm run build
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  verbose: true
  target-branch: master
  on:
    branch: source